# -*- coding: utf-8 -*-
# Unterkategorien/Geschichte/antike.py

SUBDISCIPLINES = [
    ("Frühantike Hochkulturen (Überblick)", 7, (5,10)),
    ("Mesopotamien: Sumerer, Babylonier, Assyrer", 7, (7,10)),
    ("Ägypten: Altes, Mittleres und Neues Reich", 7, (5,10)),
    ("Pharaonentum & göttliche Herrschaft", 5, (7,10)),
    ("Pyramidenbau & Grabkultur", 5, (5,10)),
    ("Schriftentwicklung: Keilschrift & Hieroglyphen", 5, (5,10)),
    ("Rechtssysteme (z. B. Codex Hammurapi)", 5, (7,10)),
    ("Handel & frühe Stadtstaaten", 3, (3,10)),
    ("Frühe Wissenschaften (Astronomie, Mathematik)", 3, (3,10)),
    ("Basis – Frühantike (Götter, Herrscher, Städte, Symbole)", 3, (1,10)),

    ("Antikes Griechenland (Überblick)", 7, (5,10)),
    ("Mykenische & minoische Kultur", 5, (7,10)),
    ("Dunkle Jahrhunderte & Entstehung der Polis", 5, (7,10)),
    ("Polis-System: Athen & Sparta", 7, (5,10)),
    ("Demokratie in Athen", 7, (3,10)),
    ("Spartanisches System & Heloten", 5, (7,10)),
    ("Perserkriege", 7, (5,10)),
    ("Peloponnesischer Krieg", 7, (7,10)),
    ("Griechische Kolonisation", 5, (7,10)),
    ("Hellenistische Zeit (Alexander der Große)", 7, (5,10)),
    ("Kultur & Philosophie der Antike (Griechenland)", 7, (5,10)),
    ("Mythologie & Religion", 5, (3,10)),
    ("Architektur & Kunst (Tempel, Skulptur)", 5, (3,10)),
    ("Philosophen: Sokrates, Platon, Aristoteles", 7, (3,10)),
    ("Wissenschaft & Mathematik (Euklid, Archimedes)", 5, (5,10)),
    ("Olympische Spiele & Panhellenismus", 3, (3,10)),
    ("Basis – Griechenland (Götter, Poleis, Personen, Daten)", 3, (1,10)),

    ("Römische Antike (Überblick)", 7, (5,10)),
    ("Frühzeit & Königszeit Roms", 5, (7,10)),
    ("Römische Republik", 7, (5,10)),
    ("Senat & Magistrate", 5, (7,10)),
    ("Ständekämpfe (Patrizier vs. Plebejer)", 5, (7,10)),
    ("Ausdehnung Italiens & Punische Kriege", 7, (5,10)),
    ("Hannibal & Rom-Karthago-Konflikt", 5, (5,10)),
    ("Krise der Republik & Bürgerkriege", 7, (7,10)),
    ("Caesar, Pompeius, Crassus (Triumvirat)", 5, (5,10)),
    ("Übergang zur Kaiserzeit (Augustus)", 7, (5,10)),
    ("Römisches Kaiserreich: Prinzipat & Dominat", 7, (7,10)),
    ("Pax Romana", 5, (5,10)),
    ("Römische Armee & Verwaltung", 5, (5,10)),
    ("Provinzsystem & Romanisierung", 5, (5,10)),
    ("Recht & Gesellschaft (Zwölftafelgesetz, ius civile)", 7, (5,10)),
    ("Sklaverei & soziale Strukturen", 5, (5,10)),
    ("Kaiserzeit: Nero bis Commodus", 3, (3,10)),
    ("Spätantike & Völkerwanderung", 5, (5,10)),
    ("Untergang des Weströmischen Reichs", 7, (5,10)),
    ("Basis – Rom (Ämter, Daten, Kaiser, Kriege, Begriffe)", 3, (1,10)),

    ("Alltag in der Antike", 5, (3,10)),
    ("Familie & Frauenrolle", 3, (3,10)),
    ("Bildung & Erziehung (paideia)", 5, (5,10)),
    ("Religion & Kulte (Mysterienkulte, Isis, Mithras)", 5, (7,10)),
    ("Philosophie der Spätantike (Stoiker, Epikureer)", 5, (5,10)),
    ("Literatur (Epen, Tragödien, Komödien)", 5, (3,10)),
    ("Rhetorik & Geschichtsschreibung", 5, (5,10)),
    ("Architektur & Städtebau (Forum, Amphitheater)", 7, (5,10)),
    ("Technik & Ingenieurskunst (Aquädukte, Straßenbau)", 5, (5,10)),
    ("Wissenschaftliche Errungenschaften (Medizin, Astronomie)", 3, (3,10)),
    ("Kleidung, Ernährung, Hygiene", 3, (1,10)),
    ("Basis – Kultur & Alltag (Zuordnungen: Bauwerke, Autoren, Gattungen)", 3, (1,10)),

    ("Handel & Wirtschaft im Mittelmeerraum", 5, (5,10)),
    ("Phönizier & Karthago", 5, (7,10)),
    ("Etrusker & frühes Italien", 3, (3,10)),
    ("Kelten & Germanen im Kontakt mit Rom", 5, (5,10)),
    ("Persisches Großreich (Achaimeniden)", 7, (7,10)),
    ("Hellenistische Königreiche (Ptolemäer, Seleukiden)", 5, (7,10)),
    ("Beziehungen Rom–Orient", 5, (7,10)),
    ("Afrika & Nubien in der Antike", 3, (3,10)),
    ("China & Seidenstraße (frühe Kontakte)", 3, (3,10)),
    ("Basis – Mittelmeer & Kontakte (Völker, Routen, Güter, Orte)", 3, (1,10)),

    ("Übergang von Antike zu Mittelalter", 7, (7,10)),
    ("Christianisierung & Konstantin der Große", 7, (5,10)),
    ("Spätantike Philosophie (Neuplatonismus)", 5, (7,10)),
    ("Byzanz als Fortsetzung der Antike", 5, (5,10)),
    ("Römisches Erbe im Mittelalter", 5, (5,10)),
    ("Rezeption der Antike in Renaissance & Humanismus", 5, (5,10)),
    ("Antikenbild in der Moderne", 3, (3,10)),
    ("Basis – Nachwirkungen (Epochen, Begriffe, Schlüsselereignisse)", 3, (1,10)),
]
